[[plugins]]                                                                                          
repo = 'Shougo/dein.vim' 
 
[[plugins]] 
repo = 'Shougo/vimproc.vim' 
build = 'make' 
 
[[plugins]] 
repo = 'thinca/vim-quickrun' 
hook_add = ''' 
    let g:quickrun_config = { 
        \ '_' : { 
            \ 'runner' : 'vimproc', 
            \ 'runner/vimproc/updatetime' : 40, 
            \ 'outputter' : 'error', 
            \ 'outputter/error/success' : 'buffer', 
            \ 'outputter/error/error'   : 'quickfix', 
            \ 'outputter/buffer/split' : ':botright 8sp', 
        \ } 
    \} 
 
    " 実行時に前回の表示内容をクローズ&保存してから実行 
    let g:quickrun_no_default_key_mappings = 1 
    nnoremap <Leader>r :cclose<CR>:write<CR>:QuickRun -mode n<CR> 
    nnoremap <Leader>, :cclose<CR>:write<CR>:QuickRun -input input.txt<CR> 
''' 
 
[[plugins]] 
repo =  'preservim/nerdtree' 
hook_add = ''' 
    nnoremap <C-n> :NERDTreeToggle<CR> 
'''
[[plugins]]
repo = 'itchyny/lightline.vim' 
hook_add = ''' 
    let g:lightline = {'colorscheme': 'seoul256'}
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'simeji/winresizer' 
